version: 2.1

workflows:
  workflow:
    jobs:
      - linux-test:
          name: "SDK 4.x PHP >=7.3 & <8.0"
          matrix:
              parameters:
                  php-version: ["7.3", "7.4"]
                  composer-dependencies: ["lowest", "highest"]
                  shared-tests: ["4.x-dev"]
      - linux-test:
          name: "SDK 4.x PHP >=8.0"
          matrix:
              parameters:
                  php-version: ["8.0", "8.1"]
                  composer-dependencies: ["lowest"]
                  shared-tests: ["4.x-dev"]
      - linux-test:
          name: "SDK 5.x PHP >=8.0"
          matrix:
              parameters:
                  php-version: ["8.0", "8.1"]
                  composer-dependencies: ["highest"]
                  shared-tests: ["dev-main"]

jobs:
  linux-test:
    parameters:
      php-version:
        type: string
      composer-dependencies:
        type: string
      shared-tests:
        type: string

    docker:
      - image: cimg/php:<<parameters.php-version>>
      - image: redis

    steps:
      - checkout
      - run:
          name: install dependencies
          command: composer install --no-progress
      - run:
          name: require appropriate shared tests package
          command: composer require --dev 'launchdarkly/server-sdk-shared-tests:<<parameters.shared-tests>>'
      - when:
          condition:
            equal: [ <<parameters.composer-dependencies>>, "lowest" ]
          steps:
            - run:
                name: downgrade to lowest versions
                command: composer update --prefer-lowest --prefer-stable
      - run: mkdir -p ./phpunit
      - run:
          name: run tests
          command: php vendor/bin/phpunit
      - store_test_results:
          path: ./phpunit
      - store_artifacts:
          path: ./phpunit
